# Generated by Django 4.2.27 on 2026-01-29 07:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, max_length=50)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('current_status', models.CharField(choices=[('order_received', 'Order Received'), ('sourcing', 'Sourcing Products'), ('quality_check', 'Quality Check'), ('packing', 'Packing'), ('documentation', 'Documentation & Customs'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered')], default='order_received', max_length=20)),
                ('shipping_method', models.CharField(choices=[('air', 'Air Freight'), ('sea', 'Sea Freight'), ('land', 'Land (Train)'), ('express', 'Express Courier')], max_length=20)),
                ('origin', models.CharField(default='China', max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('estimated_delivery', models.DateField(blank=True, null=True)),
                ('actual_delivery', models.DateField(blank=True, null=True)),
                ('total_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Weight (kg)')),
                ('total_packages', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('order_received', 'Order Received'), ('sourcing', 'Sourcing Products'), ('quality_check', 'Quality Check'), ('packing', 'Packing'), ('documentation', 'Documentation & Customs'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Destination'), ('delivered', 'Delivered')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='tracking.shipment')),
            ],
            options={
                'verbose_name': 'Shipment Update',
                'verbose_name_plural': 'Shipment Updates',
                'ordering': ['-timestamp'],
            },
        ),
    ]
